#### Types of Text Classification

1. binary(2-class)
2. multiclass(multiple-class)
2. multilabel(multiple-labels)

In [36]:
import numpy as np
import pandas as pd

In [37]:
temp_df = pd.read_csv('IMDB Dataset.csv')
df = temp_df.iloc[:10000]

In [38]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [39]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [40]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [41]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [42]:
df.duplicated().sum()

17

In [43]:
df.drop_duplicates(inplace=True)

C:\Users\humay\AppData\Local\Temp\ipykernel_7100\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [44]:
df.duplicated().sum()

0

In [45]:
#Basic Preprocessing
#Remove Tags
#lowercase
#remove stopwords

In [46]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [47]:
df['review'] = df['review'].apply(remove_html_tags)

C:\Users\humay\AppData\Local\Temp\ipykernel_7100\1940109292.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tags)


In [48]:
df['review'][1]

'A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [49]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\humay\AppData\Local\Temp\ipykernel_7100\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [50]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x:[item for item in x.split if item not in sw_list]).apply(lambda x:" ".join(x))

TypeError: 'builtin_function_or_method' object is not iterable

In [ ]:
df

review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [ ]:
X=df.iloc[:,0:1]
y =df['sentiment']

In [ ]:
X

review
0     one of the other reviewers has mentioned that ...
1     a wonderful little production. the filming tec...
2     i thought this was a wonderful way to spend ti...
3     basically there's a family where a little boy ...
4     petter mattei's "love in the time of money" is...
...                                                 ...
9995  fun, entertaining movie about wwii german spy ...
9996  give me a break. how can anyone say that this ...
9997  this movie is a bad movie. but after watching ...
9998  this is a movie that was probably made to ente...
9999  smashing film about film-making. shows the int...

[9983 rows x 1 columns]

In [ ]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...   
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y=encoder.fit_transform(y)

In [ ]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [56]:
print(X_trian.shape,X_test.shape)

(7986, 1) (1997, 1)


In [ ]:
#Applying Bag Of Words
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer()

In [58]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()
print(X_train_bow.shape,X_test_bow.shape)

(7986, 48284) (1997, 48284)


In [59]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

In [60]:
gnb.fit(X_train_bow,y_train)

GaussianNB()

In [61]:
print(X_test_bow.shape,X_train_bow.shape)
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

(1997, 48284) (7986, 48284)


0.6364546820230346

In [62]:
confusion_matrix(y_test,y_pred)

array([[716, 236],
       [490, 555]], dtype=int64)

In [63]:
from sklearn.ensemble import RandomForestClassifier
rf= RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8382573860791187

In [64]:
cv = CountVectorizer(max_features=3000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf= RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)


0.8437656484727091

#### N-grams

In [65]:
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

rf= RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.829744616925388

#### Tfidf

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [67]:
tfidf = TfidfVectorizer()

In [68]:
X_train_bow = tfidf.fit_transform(X_train['review']).toarray()
X_test_bow = tfidf.transform(X_test['review']).toarray()

rf= RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8357536304456685

### Word2VEC

In [69]:
import gensim

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [70]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [71]:
model = gensim.models.Word2Vec(window=10,min_count=2)

In [72]:
model.build_vocab(story)

In [73]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(8322414, 10950890)

In [74]:
len(model.wv.index_to_key)

31846

In [80]:
def document_vector(doc):
    #remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [81]:
document_vector(df['review'].values[0])

array([ 0.10044722,  0.10157217, -0.11738639, -0.19526133,  0.35935235,
       -0.2155898 ,  0.42203343,  0.41389787,  0.1708819 , -0.1630134 ,
       -0.11570194, -0.3878615 , -0.11242823, -0.373776  ,  0.05541541,
        0.03497395,  0.17063582,  0.08438548, -0.4418039 ,  0.04095962,
       -0.048406  , -0.12270574, -0.7716778 , -0.52000904, -0.0421349 ,
       -0.03903252,  0.13238922, -0.13590671, -0.29980975, -0.20029093,
       -0.1369229 ,  0.01405265, -0.07853388, -0.5576248 , -0.3702845 ,
        0.50102973,  0.53884465, -0.05595363, -0.36281326, -0.60843885,
        0.06142555, -0.43894154,  0.41861215, -0.10940237,  0.32133976,
        0.16802937, -0.59223795, -0.10660974,  0.1324715 ,  0.04328262,
       -0.36093894, -0.59178865,  0.35362878, -0.17595811,  0.10655044,
       -0.13683775,  0.27909005,  0.31388408, -0.4181435 ,  0.46855384,
        0.07314098, -0.00368251, -0.4255624 , -0.535954  ,  0.02362024,
        0.37391827,  0.22286609,  0.29313767, -0.47283602,  0.19

In [82]:
from tqdm import tqdm

In [84]:
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [23:33<00:00,  7.06it/s]  


In [85]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [86]:
rf= RandomForestClassifier()

rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7621432148222334